### ISSUE TITLE
Add AdvancedMusicPlayer Class

### ISSUE THREAD

**Issue by TheFuzzyRiolu** [watercolor-games/peace-engine#4]
The `AdvancedMusicPlayer` class is a theoretical Peace Engine entity that takes in a path to a folder in the Content Pipeline containing a bunch of `.ogg` audio files. Each file has a name in the format `xxxx_y.ogg`, where `xxxx` is a number indicating the order in which the audio file should be played - it is encoded in hexadecimal. `y` is a binary digit determining whether the audio file is looped.

The class would then load all the audio files in the order described by their file names, and allow the developer to set which file is currently playing, apply pitch-shifts, set the volume, etc. The entity would manage the looping and seamlessly moving to the next track when the current track hits the end point and the developer switches the `CurrentTrack` property to a new value.

A method would also be in place that - when called - fades out the current segment, and stops the entity from playing its audio, allowing for a graceful stop of the audio track. The method would take in a single `double` as an argument indicating the time in seconds of the fade-out transition.

A similar method should also be implemented for fade-pausing, so you can fade out and pause the track, and resume+fade-in later.

### Use cases

In The Peacenet, certain tracks by Anders Jensen are split into loopable and seamless segments. This includes the game's main menu soundtrack, the tutorial music, as well as some mission themes (namely, the end-game mission's theme, Don't Sleep). Currently, each song has its own entity that manages the segments and looping, etc. Why make this hard on ourselves? It's hard enough actually MAKING the seamless segments in Audacity, why should we keep writing separate loop entities for them? A single class like this would get rid of some of those headaches.

### To-do

 - [ ] Implement the file-name decoder
 - [ ] Implement the actual loop code
 - [ ] Implement fade-in and fade-out methods for stopping, pausing, and playing the track
 - [ ] Add `Volume`, `PitchShift`, and `Apply3D` properties/methods on top of the normal `SoundEffectInstance` ones in MonoGame.
 - [ ] Testing. Lots and lots of testing.

**Comment by NetwideRogue** [comment]
Store the song as one audio file and one Audacity labels file that determines where the loop points are.

**Comment by TheFuzzyRiolu** [comment]
What do Audacity label files even look like? Might look into that.
